#!/usr/bin/env python3
"""Verify filter tool installation and .ugrep configuration."""

import shutil
import subprocess
import sys
from pathlib import Path

# Filter tools and their requirements
FILTER_TOOLS = {
    "pdftotext": {
        "package": "poppler-utils",
        "formats": ["PDF"],
        "required": True,
        "test_cmd": ["pdftotext", "-v"],
    },
    "pandoc": {
        "package": "pandoc",
        "formats": ["DOCX", "ODT", "EPUB", "HTML", "RTF", "XML"],
        "required": False,
        "test_cmd": ["pandoc", "--version"],
    },
    "antiword": {
        "package": "antiword",
        "formats": ["DOC (legacy)"],
        "required": False,
        "test_cmd": ["antiword", "-v"],
    },
    "jq": {
        "package": "jq",
        "formats": ["JSON"],
        "required": False,
        "test_cmd": ["jq", "--version"],
    },
}


def check_tool_installed(name: str) -> bool:
    """Check if tool is available in PATH."""
    return shutil.which(name) is not None


def verify_tool_works(name: str, test_cmd: list[str]) -> tuple[bool, str]:
    """Verify tool actually works by running test command."""
    try:
        result = subprocess.run(
            test_cmd,
            capture_output=True,
            text=True,
            timeout=5,
        )
        return True, result.stdout.split("\n")[0]
    except (subprocess.TimeoutExpired, FileNotFoundError, Exception) as e:
        return False, str(e)


def verify_ugrep_config(config_path: Path) -> tuple[bool, list[str]]:
    """Verify .ugrep configuration file."""
    issues = []

    if not config_path.exists():
        issues.append("File does not exist")
        return False, issues

    try:
        content = config_path.read_text(encoding="utf-8")
    except Exception as e:
        issues.append(f"Cannot read file: {e}")
        return False, issues

    # Check for filter lines
    filter_count = content.count("--filter=")
    if filter_count == 0:
        issues.append("No filters defined")

    # Check for generated marker
    if "Generated by contextfs" not in content:
        issues.append("Missing generation marker (may be manually edited)")

    return len(issues) == 0, issues


def main():
    print("=" * 60)
    print("ContextFS Filter Tool Verification")
    print("=" * 60)
    print()

    # Check each tool
    results = {}
    for name, info in FILTER_TOOLS.items():
        installed = check_tool_installed(name)

        if installed:
            works, version = verify_tool_works(name, info["test_cmd"])
            status = "✅ Installed" if works else "⚠️  Installed but not working"
            results[name] = works
            print(f"{status:20} {name:15} - Formats: {', '.join(info['formats'])}")
            if works and version:
                print(f"{'':20} {'':15}   Version: {version}")
        else:
            status = "❌ REQUIRED" if info["required"] else "⚠️  Optional"
            results[name] = False
            print(f"{status:20} {name:15} - Install: {info['package']}")
            print(f"{'':20} {'':15}   Formats: {', '.join(info['formats'])}")
        print()

    # Check .ugrep configuration if exists
    print("-" * 60)
    print(".ugrep Configuration File Check")
    print("-" * 60)

    # Look in common locations
    ugrep_paths = [
        Path.cwd() / ".ugrep",
        Path.home() / ".ugrep",
    ]

    found_config = False
    for ugrep_path in ugrep_paths:
        if ugrep_path.exists():
            found_config = True
            print(f"Found: {ugrep_path}")
            valid, issues = verify_ugrep_config(ugrep_path)

            if valid:
                print("✅ Configuration valid")
            else:
                print("⚠️  Configuration issues:")
                for issue in issues:
                    print(f"   - {issue}")
            print()

    if not found_config:
        print("ℹ️  No .ugrep file found (will be generated by server)")
        print()

    # Summary
    print("=" * 60)
    print("Summary")
    print("=" * 60)

    installed_count = sum(results.values())
    total_count = len(FILTER_TOOLS)

    print(f"Installed tools: {installed_count}/{total_count}")

    required_missing = [
        name for name, info in FILTER_TOOLS.items() if info["required"] and not results[name]
    ]

    if required_missing:
        print(f"❌ Missing required tools: {', '.join(required_missing)}")
        print()
        print("Installation commands:")
        for tool in required_missing:
            info = FILTER_TOOLS[tool]
            print(f"  macOS:  brew install {info['package']}")
            print(f"  Linux:  sudo apt install {info['package']}")
        sys.exit(1)
    else:
        print("✅ All required tools installed")

        optional_count = len(
            [name for name, info in FILTER_TOOLS.items() if not info["required"] and results[name]]
        )
        print(f"✅ {optional_count} optional tools installed")

        if installed_count < total_count:
            print()
            print("ℹ️  To enable more formats, install:")
            for name, info in FILTER_TOOLS.items():
                if not results[name] and not info["required"]:
                    print(f"  - {name}: {info['package']}")
                    print(f"    Enables: {', '.join(info['formats'])}")

        sys.exit(0)


if __name__ == "__main__":
    main()
